import Image from 'next/image'
import { DynaPuff, Inter } from 'next/font/google'
import Head from 'next/head'
import { BsFillMoonStarsFill } from 'react-icons/bs'
import { 
  AiFillTwitterCircle,
  AiFillLinkedin,
  AiFillGithub
 } from 'react-icons/ai'

import DoorDrop from '../../public/DoorDrop.jpg'
import design from '../../public/design.png'
import code from '../../public/code.png'
import consulting from '../../public/consulting.png'
import mahalon from '../../public/mahalon.jpeg'
import poolr from '../../public/Poolr.jpg'
import poolrDriver from '../../public/PoolrDriver.jpg'
import { Typography } from "@material-tailwind/react";

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div className='text-black' >
      <Head>
        <title>Mahalon Owino Ochieng</title>
        <meta name="description" content="generated by mahalon Owino"/>
      </Head>
    <main className='bg-white px-10 md:px-20 lg:px-40'>
      <section className=" min-h-screen">
        <nav className='py-10 mb-12 flex justify-between'>
          <h1 className='text-black'>MAHALON OWINO</h1>
          <ul className='flex justify-center'>
            <li><BsFillMoonStarsFill/></li>
            <li >
              <a className='bg-gray-800 text-white px-4 py-2 border-none rounded-md ml-8'>Resume</a>
            </li>
          </ul>
        </nav>
        <div className='text-center p-10'>
        <h2 className='text-5xl py-2 text-gray-800 font-medium md:text-6xl'>Mahalon Owino</h2>
        <h3 className='text-2xl py-2 md:text-3xl'>Developer</h3>

        <p className='text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto'>
        I am a recent graduate of Computer Science and a largely self-taught
full-stack developer who has experience implementing solutions
using, Java Spring framework, Angular, Typescript, React, JavaScript
and rest APIs among others. I am highly analytical and an effective
problem-solver, who thrives in a collaborative atmosphere to deliver
quality results.
        </p>

      </div>
      <div className='text-5xl flex justify-center gap-16 py-3 text-gray-400'>
        <a><AiFillTwitterCircle/></a>
        <a><AiFillGithub/></a>
        <a><AiFillLinkedin/></a>
      </div>
      <div className='relative bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-20 mx-auto overflow-hidden md:h-96 md:w-96'>
        <Image src={mahalon} alt="alternative"  layout='fill' objectFit='cover' />
      </div>
      </section>
      <section>
        <div className='text-left p-10 mt-20'>
          <h2  className='text-2xl py-2 mb-2 mt-0 text-4xl font-medium leading-tight text-primary'>Services I  offer</h2>
          <p className='text-md py-5 leading-8 text-gray-800'> Self-Taught, Always learning ,Full Stack Developer with strong knowledge in developing web apps. Effective at problem-solving and project management, with a focus on delivering quality results.</p>
          

        </div>
        <div className='lg:flex gap-10'>
        <div className='text-center shadow-lg p-10 rounded-xl my-10 hover:shadow-2xl transition delay-150 duration-175 ease-in-out '>
          <Image src={design} alt='alt' width={50} height={50} className='m-auto'/>
          <h3 className='text-lg font-medium pt-8 pb-2'>Front End Engineering</h3>
          <p className='py-2'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto eligendi aperiam assumenda quam optio tempore quo vero? Dolorem impedit quaerat nisi amet assumenda repellat vel consequuntur aperiam, minima fugiat rerum?</p>
          <h4 className='py-4 text-teal-500'>Tools</h4>
          <p className="text-gray-800 py-1">Java</p>
          <p className="text-gray-800 py-1">Java</p>
          <p className="text-gray-800 py-1">Java</p>
          <p className="text-gray-800 py-1">Java</p>
          <p className="text-gray-800 py-1">Java</p>
        </div>
        <div className='text-center shadow-lg p-10 rounded-xl my-10 hover:shadow-2xl transition delay-150 duration-175 ease-in-out'>
          <Image src={code} alt='alt' width={50} height={50} className='m-auto' />
          <h3 className='text-lg font-medium pt-8 pb-2'>Front End Engineering</h3>
          <p className='py-2'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto eligendi aperiam assumenda quam optio tempore quo vero? Dolorem impedit quaerat nisi amet assumenda repellat vel consequuntur aperiam, minima fugiat rerum?</p>
          <h4 className='py-4 text-teal-500'>Tools</h4>
          <p className="text-gray-800 py-1">Java</p>
          <p className="text-gray-800 py-1">Java</p>
          <p className="text-gray-800 py-1">Java</p>
          <p className="text-gray-800 py-1">Java</p>
          <p className="text-gray-800 py-1">Java</p>
        </div>
        <div className='text-center shadow-lg p-10 rounded-xl my-10 hover:shadow-2xl transition delay-150 duration-175 ease-in-out '>
          <Image src={consulting} alt='alt' width={50} height={50} className='m-auto' />
          <h3 className='text-lg font-medium pt-8 pb-2'>Front End Engineering</h3>
          <p className='py-2'>Lorem ipsum dolor sit amet consectetur adipisicing elit. Architecto eligendi aperiam assumenda quam optio tempore quo vero? Dolorem impedit quaerat nisi amet assumenda repellat vel consequuntur aperiam, minima fugiat rerum?</p>
          <h4 className='py-4 text-teal-500'>Tools</h4>
          <p className="text-gray-800 py-1">Java</p>
          <p className="text-gray-800 py-1">Java</p>
          <p className="text-gray-800 py-1">Java</p>
          <p className="text-gray-800 py-1">Java</p>
          <p className="text-gray-800 py-1">Java</p>
        </div>
        </div>

        <h2  className='text-2xl py-2 mb-20 mb-2 mt-0 text-4xl font-medium leading-tight text-primary'>Some of my work</h2>
        <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
        <div className='basis-1/3 object-fill flex-1'>
        <h3  className='text-2xl py-2 mb-20'>Door Drop</h3>
        <Image src={DoorDrop} alt="alternative" className='rounded-lg object-cover'  layout='responsive'/>
          <p className='text-md py-5 leading-8 text-gray-800'>   L
          ipsam aliquid quae architecto nam repudiandae quia, quidem eligendi culpa.</p>
            <p className='text-md py-5 leading-8 text-gray-800'>   Lorem ipsum dolor sit, amet consectetur adipisicing elit.
          Possimus aspernatur ea natus consequuntur error commodi doloremque magni distinctio cupiditate quibusdam,
          ipsam aliquid quae architecto nam repudiandae quia, quidem eligendi culpa.</p>

        </div>
        <div className='basis-1/3 object-fill flex-1'>
        <h3  className='text-2xl py-2 mb-20'>Poolr</h3>
        <Image src={poolr} alt="alternative" className='rounded-lg object-cover'  layout='responsive'/>
          <p className='text-md py-5 leading-8 text-gray-800'>   L
          ipsam aliquid quae architecto nam repudiandae quia, quidem eligendi culpa.</p>
            <p className='text-md py-5 leading-8 text-gray-800'>   Lorem ipsum dolor sit, amet consectetur adipisicing elit.
          Possimus aspernatur ea natus consequuntur error commodi doloremque magni distinctio cupiditate quibusdam,
          ipsam aliquid quae architecto nam repudiandae quia, quidem eligendi culpa.</p>

        </div>
        <div className='basis-1/3 object-fill flex-1'>
        <h3  className='text-2xl py-2 mb-20'>Poolr Driver</h3>
        <Image src={poolrDriver} alt="alternative" className='rounded-lg object-cover'  layout='responsive'/>
          <p className='text-md py-5 leading-8 text-gray-800'>   L
          ipsam aliquid quae architecto nam repudiandae quia, quidem eligendi culpa.</p>
            <p className='text-md py-5 leading-8 text-gray-800'>   Lorem ipsum dolor sit, amet consectetur adipisicing elit.
          Possimus aspernatur ea natus consequuntur error commodi doloremque magni distinctio cupiditate quibusdam,
          ipsam aliquid quae architecto nam repudiandae quia, quidem eligendi culpa.</p>

        </div>
        <div className='basis-1/3 object-fill flex-1'>
        <h3  className='text-2xl py-2 mb-20'>Poolr Driver</h3>
        <Image src={poolrDriver} alt="alternative" className='rounded-lg object-cover'  layout='responsive'/>
          <p className='text-md py-5 leading-8 text-gray-800'>   L
          ipsam aliquid quae architecto nam repudiandae quia, quidem eligendi culpa.</p>
            <p className='text-md py-5 leading-8 text-gray-800'>   Lorem ipsum dolor sit, amet consectetur adipisicing elit.
          Possimus aspernatur ea natus consequuntur error commodi doloremque magni distinctio cupiditate quibusdam,
          ipsam aliquid quae architecto nam repudiandae quia, quidem eligendi culpa.</p>

        </div>
        </div>
      </section>
    </main>
    <footer className="w-full bg-white p-8">
 
      <hr className="my-8 border-blue-gray-50" />
      <Typography color="blue-gray" className="text-center font-normal">
        &copy; 2023 Mahalon Owino
      </Typography>
    </footer>

    </div>
  )
}
